{"uid":"cf42a069d711b0a1","name":"Delete all books in the user profile","fullName":"tests.api_tests.book_store_test.TestBookStore#test_delete_all_books_in_the_profile","historyId":"5d75b5febce711eaac7362d3c23ef293","time":{"start":1724663281833,"stop":1724663281833,"duration":0},"status":"failed","statusMessage":"AssertionError: 406","statusTrace":"@pytest.fixture(scope='function', autouse=True)\n    def account_setup():\n        account_api = AccountAPI()\n>       user_id = account_api.create_user()\n\ntests/api_tests/conftest.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nservices/account/api_account.py:25: in create_user\n    self.assert_response_status_code(response, 201)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <services.account.api_account.AccountAPI object at 0x7fa98559e870>\nresponse = <Response [406]>, status_code = 201\n\n    def assert_response_status_code(self, response, status_code):\n        with allure.step(f\"Check response status code is {status_code}\"):\n>           assert response.status_code == status_code, response.status_code\nE           AssertionError: 406\n\nutils/helper.py:14: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1724663274967,"stop":1724663275095,"duration":128},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"account_setup","time":{"start":1724663281834,"stop":1724663282142,"duration":308},"status":"failed","statusMessage":"AssertionError: 406\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1139, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/usr/workspace/tests/api_tests/conftest.py\", line 8, in account_setup\n    user_id = account_api.create_user()\n              ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/services/account/api_account.py\", line 25, in create_user\n    self.assert_response_status_code(response, 201)\n  File \"/usr/workspace/utils/helper.py\", line 14, in assert_response_status_code\n    assert response.status_code == status_code, response.status_code\n","steps":[{"name":"Create user","time":{"start":1724663281835,"stop":1724663282142,"duration":307},"status":"failed","statusMessage":"AssertionError: 406\n","statusTrace":"  File \"/usr/local/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/usr/workspace/services/account/api_account.py\", line 25, in create_user\n    self.assert_response_status_code(response, 201)\n  File \"/usr/workspace/utils/helper.py\", line 14, in assert_response_status_code\n    assert response.status_code == status_code, response.status_code\n","steps":[{"name":"Check response status code is 201","time":{"start":1724663282141,"stop":1724663282141,"duration":0},"status":"failed","statusMessage":"AssertionError: 406\n","statusTrace":"  File \"/usr/workspace/utils/helper.py\", line 14, in assert_response_status_code\n    assert response.status_code == status_code, response.status_code\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":1,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":2,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"afterStages":[],"labels":[{"name":"epic","value":"API Tests"},{"name":"feature","value":"Book Store"},{"name":"parentSuite","value":"tests.api_tests"},{"name":"suite","value":"book_store_test"},{"name":"subSuite","value":"TestBookStore"},{"name":"host","value":"3589f515350a"},{"name":"thread","value":"1-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.api_tests.book_store_test"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":2,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"e97539a19436c2eb","reportUrl":"https://vvkobzar.github.io/aqa_pet_project/20//#testresult/e97539a19436c2eb","status":"failed","statusDetails":"AssertionError: 406","time":{"start":1724663282902,"stop":1724663282902,"duration":0}}]},"tags":[]},"source":"cf42a069d711b0a1.json","parameterValues":[]}